type Task {
  id:ID!
  firstname: String!
  lastname: String!
}
type Workspace {
  id:ID!
  name: String!

}

type Query {
  tasks: [Task]
  workspaces: [Workspace]

}
type Mutation {
  addTask(
    firstname: String!
    lastname: String!
  ): Task!
  updateTask(
    id: ID!
    firstname: String!
    lastname: String!
  ): Task!
  deleteTask(
    id: ID!
  ): Boolean!

  addWorkspace(
    name: String!
  ): Workspace!
  updateWorkspace(
    id: ID!
    name: String!
  ): Workspace!
  deleteWorkspace(
    id: ID!
  ): Boolean!
}
