type Post {
  firstname: String!
  lastname: String!
}

type PostsPage {
  posts: [Post]
  hasMore: Boolean
}
type Query {

  getPosts: [Post]

}
type Mutation {
  addPost(
    firstname: String!
    lastname: String!
  ): Post!
}
