type Post {
  firstname: String!
  lastname: String!
}

type PostsPage {
  posts: [Post]
  hasMore: Boolean
}
type Query {

  getTask: [Post]

}
type Mutation {
  addTask(
    firstname: String!
    lastname: String!
  ): Post!
  updateTask(
    id: ID!
    firstname: String!
    lastname: String!
  ): Post!
  deleteTask(
    id: ID!
  ): Post!
  
}
