type Post {
  firstname: String!
  lastname: String!
}

type PostsPage {
  posts: [Post]
  hasMore: Boolean
}
type Query {

  getTask: [Post]

}
type Mutation {
  addPost(
    firstname: String!
    lastname: String!
  ): Post!
  updatePost(
    id: ID!
    firstname: String!
    lastname: String!
  ): Post!
  
}
